### ISSUE TITLE
What does the trait Gender play in the WIR.scala file?

### ISSUE THREAD

**Issue by kai413629305** [freechipsproject/firrtl#1054]
What does the trait Gender play in the WIR.scala file?
`trait Gender`
`case object MALE extends Gender`
`case object FEMALE extends Gender`
`case object BIGENDER extends Gender`
`case object UNKNOWNGENDER extends Gender`

**Comment by edwardcwang** [comment]
See page 47 in the spec https://github.com/freechipsproject/firrtl/blob/master/spec/spec.pdf

**Comment by kai413629305** [comment]
> See page 47 in the spec https://github.com/freechipsproject/firrtl/blob/master/spec/spec.pdf

Thank you for your answer!

**Comment by seldridge** [comment]
Going to go ahead and close this as I *think* this is resolved. If not, feel free to re-open.
