### ISSUE TITLE
Let user specify the destination filename for "firrtl_black_box_resource_files.f"

### ISSUE THREAD

**Issue by jerryz123** [freechipsproject/firrtl#1090]
**Type of issue**: feature request 

  * **What is the current behavior?** The BlackBoxResourceHelper always emits the filelist into the file "firrtl_black_box_resource_files.f". 
  * **What is the expected behavior?** Allow the destination file of the BlackBoxResouceHelper to be manually specified. 

**What is the use case for changing the behavior?** We want to avoid clobbering the resource_files.f when running multiple invocations of FIRRTL in one directory.

**Impact**: API addition (no impact on existing code)

**Development Phase**: request

**Comment by albert-magyar** [comment]
Closed by #1129
