### ISSUE TITLE
README.md tutorial updates

### ISSUE THREAD

**Issue by juliusbaxter** [freechipsproject/firrtl#1112]
**Type of issue**: bug report

  * **What is the current behavior?**

Two things in the README need a refresh.

First is that the prerequisites should be updated to include yosys else a handful of things fail during `sbt test`.

Second is that when attempting to run a custom transform tutorial, we get told the following:

```
/utils/bin/firrtl -td regress -tn rocket --custom-transforms tutorial.lesson1.AnalyzeCircuit
------------------------------------------------------------------------------
Error: Option --top-name failed when given ''. Option '--top-name/-tn' was removed as part of the FIRRTL Stage refactor. Use an explicit input/output options instead.
This error will be removed in 1.3.
Try --help for more information.
------------------------------------------------------------------------------
```

**Comment by seldridge** [comment]
Thanks for identifying and reporting these issues. :+1:

#1113 fixes these narrowly. However, with the advent of 3.2/1.2, this is likely the time for a broader README overhaul. Chisel is in much better shape than it was before after ([Chisel#1106](https://github.com/freechipsproject/chisel3/pull/1106)) and associated PRs. FIRRTL likely needs similar treatment. Additionally, I need to get the new Chisel website better integrated with this, notably, using `tut` to make sure that problems like the `--custom-transforms` example are tested.
