### ISSUE TITLE
Connecting AnalogType within BundleTypes

### ISSUE THREAD

**Issue by abejgonzalez** [freechipsproject/firrtl#1159]
**Type of issue**: bug report

  * **If possible, please directly provide the FIRRTL file or a relevant fragment if the file is large**
```scala
case oldParentInstance @ WDefInstance(_, _, parentTemplate.module, _) =>
  val retypedParentInst = oldParentInstance.copy(tpe = parentTemplate.tpe)
  val childPeerInst = childTemplate.copy(name = namespace.newName(oldParentInstance.name + "_" + childTemplate.name))
  promotedNames += childPeerInst.name
  val connection = Connect(childTemplate.info, instanceField(retypedParentInst, childTemplate.name), instanceRef(childPeerInst))
  Block(Seq(retypedParentInst, childPeerInst, connection))
case Block(stmts) => Block(stmts map (s => transformParentInstances(s, parentTemplate, childTemplate, namespace, promotedNames)))
case s => s
```

  * **What is the current behavior?**
This fragment is part of a larger transformation that brings a module up the hierarchy. The `Connect` statement is used to attach the IO of the block moved to its parent (which now resides in the same level of the hierarchy). However, within the IO bundle is a `AnalogType` which fails with an `firrtl.passes.CheckTypes$InvalidConnect: .... Type mismatch`.

  * **What is the expected behavior?**
The `Connect` statement should connect the `Analog` IOs. (Unless there is another way to connect them?)

  * **Please tell us about your environment:**
FIRRTL Hash: 99ae1d6649f1731c5dec2098b10733735232b72c

**Impact**: unknown

**Development Phase**: request

**Other information**

**Comment by albert-magyar** [comment]
Resolved: use partial connects
