### ISSUE TITLE
Improve error message for combinational loops

### ISSUE THREAD

**Issue by oharboe** [freechipsproject/firrtl#1203]
The error message below leaves something to be desired when it comes to chasing down a combinational loop.

The trick that I've found is to bring up the generated .fir file and from there, I search for e.g. _T_659 and there will be an annotation in the .fir file that tells me where in the .scala file to look: Thingamabob.scala line 177

Obviosuly it would improve the error message if the references back to Chisel code lines was directly in the error message.

```
node _T_659 = eq(_T_589, UInt<1>("h00")) @[Thingamabob.scala 177:69]
```

```
[deleted]
[info]   firrtl.transforms.CheckCombLoops$CombLoopException: : [module Thingamabob] Combinational loop detected:
[info] Thingamabob._T_589
[info] Thingamabob._T_659
[info] Thingamabob._T_660
[info] Thingamabob._GEN_13
[info] Thingamabob._GEN_43
[deleted]
```

**Comment by albert-magyar** [comment]
That's a good idea, I will add the info printing to the error.

**Comment by oharboe** [comment]
@albert-magyar Thanks!
