### ISSUE TITLE
Possible typo in specification re: statement groups and parentheses

### ISSUE THREAD

**Issue by boqwxp** [freechipsproject/firrtl#1563]
### Checklist

- [x] Did you specify the current behavior?
- [x] Did you specify the expected behavior?
- [ ] Did you provide a code example showing the problem?
- [ ] Did you describe your environment?
- [ ] Did you specify relevant external information?

### What is the current behavior?

The [spec](https://github.com/freechipsproject/firrtl/blob/master/spec/spec.pdf) says this about statement groups and parentheses (p. 58):

> Statements are combined into statement groups by surrounding them
> with parenthesis. A colon at the end of a line will automatically surround
> the next indented region with parenthesis and thus create a statement group.
> The following statement:
```
when c :
	a <= b
else :
	e <= f
```
> can be equivalently expressed on a single line as follows.
```
when c : a <= b else : e <= f
```

### What is the expected behavior?

[An older copy](http://www2.eecs.berkeley.edu/Pubs/TechRpts/2016/EECS-2016-9.pdf) of the spec, which seems to make much more sense, says the following.

> Statements are combined into statement groups by surrounding them with parenthesis.
> A colon at the end of a line will automatically surround the next indented region with
> parenthesis and thus create a statement group. The following statement:
```
when c :
	a <= b
else :
	c <= d
	e <= f
```
> can be equivalently expressed on a single line as follows.
```
when c : (a <= b) else : (c <= d, e <= f)
```

Specifically, I expect to see parenthesis in the single-line alternative.

### Steps to Reproduce

Look at the spec.

### Your environment
N/A

### External Information
N/A

**Comment by seldridge** [comment]
The use of parentheses is entirely vestigial. a `when`/`else` context has to be indented if it's more than one statement. There's new language in #1565 that clarifies what is actually supported. Sorry about the confusion and thanks for giving the spec a hard read.
