### ISSUE TITLE
Should we be recommending (new TransformManager) to replace Compiler?

### ISSUE THREAD

**Issue by albert-magyar** [freechipsproject/firrtl#1585]
There are a number of deprecation warning / comments with messages like the following:
```scala
"Use 'new TransformManager(Forms.LowForm, Forms.MidForm)'. This will be removed in 1.4."
```

The `TransformManager` superclass does not include `UpdateAnnotations` as a wrapper, so running a plain `TransformManager` with a list of targets will not actually make any renaming happen between one managed transform and the next.

It seems to me that if people follow these messages literally, they may end up with broken annotations? Perhaps we should recommend `stage.transforms.Compiler` or something similar as a streamlined replacement for 1.2 stuff?

**Comment by seldridge** [comment]
Recommending `stage.transforms.Compiler` would be perfect.
