### ISSUE TITLE
[spec] Tail op name is "head"

### ISSUE THREAD

**Issue by itviewer** [freechipsproject/firrtl#1597]
In the spec.pdf
![深度截图_选择区域_20200512213606](https://user-images.githubusercontent.com/1397840/81698544-bd4b7400-9498-11ea-9777-af5f7ab30d45.png)

should it be tail?

**Comment by jackkoenig** [comment]
Yes that is a bug, I think it was introduced in https://github.com/freechipsproject/firrtl/pull/1456

**Comment by jackkoenig** [comment]
Thank you for the report!
