### ISSUE TITLE
DshlTooBig error message may makes misleadings

### ISSUE THREAD

**Issue by Soya-Onishi** [freechipsproject/firrtl#1794]
### Checklist

- [x] Did you specify the current behavior?
- [x] Did you specify the expected behavior?
- [x] Did you provide a code example showing the problem?
- [x] Did you describe your environment?
- [ ] Did you specify relevant external information?

### What is the current behavior?

When I use dshl function with shift amount bits which width is 20, I get an `DshlTooBig` error.
However, its message says "Width of dshl shift amount cannot be larger than 20 bits.", so I think it may cause misleadings about shift amount bit's width limit.

### What is the expected behavior?

Please fix error message or allow shift amount bit until 20bit.

### Steps to Reproduce

sample code is here.

```
circuit DynShl:
  module DynShl:
    input value: UInt<32>
    input shamt: UInt<20>
    output out: UInt<32>

    out <= dshl(value, shamt)
```
and error is 
```
Exception in thread "main" firrtl.passes.CheckWidths$DshlTooBig:  : [target ~DynShl|DynShl]  Width of dshl shift amount cannot be larger than 20 bits.
```

### Your environment

- firrtl Verions: v1.3.2
- OS: Linux soya 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aswaterman** [comment]
Fixed, thanks.
