### ISSUE TITLE
Question about `W` prefix.

### ISSUE THREAD

**Issue by JaewonHur** [freechipsproject/firrtl#1863]
Hi, I'm recently using FIRRTL compiler.
I don't know whether here is good place to ask, but I couldn't find any other good place.

I found definitions of `SubField`, `SubIndex` and `SubAccess` here, as seen in the spec.
I also found `WSubField`, `WSubIndex` and `WSubAccess` definitions.

It seems the classes which have `W` prefixes have one more `Flow` field.
But I can not find any other explanations in the spec.

Could anyone tell the differences between them?
Are they interchangable? 
or prefix `W` is an outcome of a lowering transforms?

**Comment by edwardcwang** [comment]
The `W` refers to the "Working IR", a set of IR nodes that extend the "standard" IR nodes with some additional information. You can see what it looks like in https://github.com/freechipsproject/firrtl/blob/master/src/main/scala/firrtl/WIR.scala

**Comment by JaewonHur** [comment]
Thanks.
