### ISSUE TITLE
Unable to checkout Submodule sim/firrtl

### ISSUE THREAD

**Issue by meowbhow** [freechipsproject/firrtl#1888]
I am trying to run NVDLA-firesim on C4 AWS instance. When i build firesim-nvlda, it gives below error

**Unable to checkout '380c233b43c2de53b0ee15a39e9364d438066b9f' in submodule path 'sim/firrtl'**

To get the module script is using below URL
https://github.com/ucb-bar/firrtl

I need your kind support to get this resolved.

**Comment by jackkoenig** [comment]
Sorry I missed this somehow but this seems to be an issue in Firesim, not in FIRRTL. Hopefully you got it resolved. If not, I'd ask on their mailing list: https://groups.google.com/u/1/g/firesim
