### ISSUE TITLE
modulus operator: grammar uses "rem", spec uses "mod"

### ISSUE THREAD

**Issue by nturley** [freechipsproject/firrtl#240]
The spec still refers to the modulus operator as "mod" instead of what [the grammar calls "rem"](https://github.com/ucb-bar/firrtl/blob/cca37c46fc0848f5dbf5f95ba60755ed6d60712b/src/main/antlr4/FIRRTL.g4#L247).

See [the modulus section](https://github.com/ucb-bar/firrtl/blob/cca37c46fc0848f5dbf5f95ba60755ed6d60712b/spec/spec.tex#L1260), and [the concrete grammar](https://github.com/ucb-bar/firrtl/blob/cca37c46fc0848f5dbf5f95ba60755ed6d60712b/spec/spec.tex#L1800).

**Comment by jackkoenig** [comment]
Fixed by #713
