### ISSUE TITLE
Constant Prop Wires as well as Nodes

### ISSUE THREAD

**Issue by jackkoenig** [freechipsproject/firrtl#414]
See https://github.com/ucb-bar/chisel3/issues/443

I believe this would remove a lot of the pointless assignments. We also might consider adding an annotation for temporary nodes so that we can use that information in choosing which names to remove. This idea relates to https://github.com/ucb-bar/firrtl/issues/378

**Comment by azidar** [comment]
related to #490

**Comment by sols1** [comment]
Another thing that would be useful is to eliminate multiple inversions of the same signal:

![chisel triple inversion](https://cloud.githubusercontent.com/assets/17886050/24519398/da8cc01e-1539-11e7-88e3-9d31883ba80f.png)

In this example:

```
_T_1795 = ~uncachedInFlight_0
_T_1797 = ~_T_1795
_T_1799 = ~_T1797
```

**Comment by sols1** [comment]
Another case of a lot of intermediate `_T` signals that should be possible to fold:

![directory_io_write_bits_data_tag](https://cloud.githubusercontent.com/assets/17886050/24567545/155c836c-1613-11e7-8cda-1e5f8ea22fe8.png)

No wonder it is hard to close toggle coverage :)

**Comment by aswaterman** [comment]
Oof.

I think constant propagation through wires will help somewhat, as well optimizing the Extract(Extract(...)) case.

**Comment by jackkoenig** [comment]
Original issue fixed by https://github.com/freechipsproject/firrtl/pull/684, will file new issue for const prop improvement
