### ISSUE TITLE
Funny Behavior when topName isn't specified

### ISSUE THREAD

**Issue by jackkoenig** [freechipsproject/firrtl#485]
The following code will emit a file called `.hi.fir` in `a/b/c`. 

```scala
    val input =
      """circuit Top :
        |  module Top :
        |    input foo : UInt<32>
        |    output bar : UInt<32>
        |    bar <= foo
        """.stripMargin
    val optionsManager = new ExecutionOptionsManager("blah") with HasFirrtlOptions {
      commonOptions = commonOptions.copy(targetDirName = "a/b/c")                                                                                                                                                       
      firrtlOptions = firrtlOptions.copy(compilerName = "high",
                                         firrtlSource = Some(input))
    }
    Driver.execute(optionsManager)
```

I'm thinking that topName is kind of a historical aberration since the Firrtl circuit itself specifies the top. IMO we should deprecate and remove it and instead use the top as specified by the circuit.

**Comment by seldridge** [comment]
FWIW, the weird top name behavior _does not exist_ with #765 applied. Using a slightly modified test:
```scala
  "Rando test" - {
    val input =
      """circuit Top :
        |  module Top :
        |    input foo : UInt<32>
        |    output bar : UInt<32>
        |    bar <= foo
        """.stripMargin
    val optionsManager = new ExecutionOptionsManager("blah",
      Array("--target-dir", "a/b/c",
            "--compiler", "high",
            "--firrtl-source", input)) with HasFirrtlExecutionOptions
    Driver.execute(optionsManager)
  }
```

```
> tree a/
a/
└── b
    └── c
        └── Top.hi.fir
```

This does nothing to address the @jackkoenig point about top name being implicit for a circuit. Note that there may be a use case of a user wanting to use `--top-name` to artificially reduce the scope of the circuit. That said, I'd be very much in favor of simplifying all the overlapping options... 1.2.0 is likely the time to do some major cleaning up here.
