### ISSUE TITLE
Automatic padframe generation

### ISSUE THREAD

**Issue by ben-k** [freechipsproject/firrtl#536]
This is a summary of the discussion at the Hurricane-2 debrief meeting.

This pass would generate a padframe based on user constraints/annotations.  @shunshou has already begun an implementation of this pass: https://github.com/ucb-bar/barstools/tree/master/tapeout/src/main/scala/transforms/pads

**Comment by albert-magyar** [comment]
Closed due to non-activity. This may belong in a user pass that acts as a flow plugin.
