### ISSUE TITLE
Emit list of modules to retime

### ISSUE THREAD

**Issue by ben-k** [freechipsproject/firrtl#539]
This is a summary of the discussion at the Hurricane-2 debrief meeting.

A Firrtl pass should emit a list of modules for which the designer intent is to retime them using the synthesis tools.  Such intent would be described in an annotation of the module in the Chisel source.

Whether this emits a simple list of names, or a properly-formatted (and potentially tool-specific) list of .tcl commands, is not decided.  But the designer intent should certainly be encoded in the source and passed through to the backend somehow.

**Comment by colinschmidt** [comment]
See https://github.com/freechipsproject/rocket-chip/pull/1333

**Comment by chick** [comment]
Consider in the future whether to move this to chisel without rocket
