### ISSUE TITLE
Support for arbitrary rearranging of the hierarchy

### ISSUE THREAD

**Issue by ben-k** [freechipsproject/firrtl#542]
This is a summary of the discussion at the Hurricane-2 debrief meeting.

This pass should, without changing the wiring/functionality of the design, allow the user to:

* Group multiple instances into a new level of hierarchy
* Ungroup or flatten a level of hierarchy, moving everything within it up one level
* Move a particular instance to an arbitrary new position in the hierarchy

The API for this is certainly up for discussion, but it was emphasized in the meeting that even something that's relatively user-unfriendly would be a vast improvement over existing options.

**Comment by albert-magyar** [comment]
This has been addressed with several feature additions, like #766, #631.
