### ISSUE TITLE
Firrtl still prints circuit serialization at log-level debug

### ISSUE THREAD

**Issue by jackkoenig** [freechipsproject/firrtl#561]
The code says logger.trace on the serialization, yet when I set log-level to debug it still prints.

**Comment by chick** [comment]
@jackkoenig is this being run with the better-logging-controls-branch or with master.  I can't see it with the better branch

**Comment by jackkoenig** [comment]
It's on master, @azidar, can you revisit your review on https://github.com/ucb-bar/firrtl/pull/488?

**Comment by jackkoenig** [comment]
Fixed by #488
