### ISSUE TITLE
support c-style hex escape sequences in strings

### ISSUE THREAD

**Issue by aswaterman** [freechipsproject/firrtl#59]
To support funky characters in string literals, C supports escaping them as using \x followed by their ASCII value in hex.  For example, \n can instead be written as \xa or \xA, and space can be written as \x20.  We should support this.  For now, I'll disallow unprintable characters in Chisel printf.

**Comment by ccelio** [comment]
I'm hitting up against an assertion error regarding this issue in my code base:

````scala
    // chisel3/internal/firrtl/IR.scala
    line 182:  require(x.toInt >= 32) // TODO \xNN once FIRRTL issue #59 is resolved  
````

**Comment by ccelio** [comment]
Not sure if this is a separate issue, but `%s` is no longer supported, even though rocket.Str is still around?

````
[INFO] Starting High Form Check
Exception in thread "main" firrtl.passes.PassExceptions: 
firrtl.passes.CheckHighForm$BadPrintfException:  @[fetch.scala 200:13]: [module FetchUnit] 
  Bad printf format: "%s"
firrtl.passes.CheckHighForm$BadPrintfIncorrectNumException:  @[fetch.scala 200:13]: 
  [module FetchUnit] Bad printf format: incorrect number of arguments
````

I use this everywhere. :(

**Comment by jackkoenig** [comment]
Firrtl does not have a String type, without that I'm not sure it's possible to create Strings in that way unfortunately :(

You could obviously rewrite simple examples as:
```scala
when (br_unit.brinfo.valid) {
  printf("BrPred V\n")
} .otherwise {
  printf("BrPred -\n")
}
```
Of course this does not scale very well at all if you want to chain a lot of similar things together. 

Thoughts on whether and how Strings should/could be supported in Firrtl @azidar, @aswaterman ?

**Comment by aswaterman** [comment]
For simple things, like that example, use %c? If the string args themselves
are constants, this could be done in Scala and doesn't require a firrtl
change.

**Comment by jackkoenig** [comment]
Yeah I forgot about %c, that would work fine. You could also probably build a super hacky string library around it using Vecs as strings.

**Comment by aswaterman** [comment]
Chisel could turn %s into a sequence of %c if the widths of the strings are
forward-inferable (a reasonable restriction IMO)

**Comment by ccelio** [comment]
Here is the git diff for BOOM required to work around not having native "%s" support:

https://github.com/ucb-bar/riscv-boom/commit/642c118cc6bc2c94fe394157845dca6facdf5bd3

It's not life threatening, but it's a sizable hit to readability of my output files.

**Comment by ekiwi** [comment]
> Firrtl does not have a String type, without that I'm not sure it's possible to create Strings in that way unfortunately :(

It seems like this is easier to handle on the Scala side. Please reopen the issue if there is still a need for supporting strings in firrtl.
