### ISSUE TITLE
Eliminate need for black_box_verilog_files.f

### ISSUE THREAD

**Issue by ucbjrl** [freechipsproject/firrtl#591]
Track @shunshou's comment from #551 

> Personally, I prefer that whatever is in generated_src or test_run_dir/DUTblahblah is fully generated by Chisel (like all black box files should be moved there) and then just, for the simulator, do generated_src/*.v... Then you don't need the .f file...

**Comment by aswaterman** [comment]
The .f file is still useful for other purposes.  I think we can just have it both ways?

**Comment by aswaterman** [comment]
Also, if you forget to "make clean" first, then looking at generated-src/*.v is not necessarily right, as it may contain files from the old build that were not overwritten by the new build.  And if "make clean" is required, something is wrong :)

**Comment by seldridge** [comment]
Closing for now. We can revisit this if people still need (don't need) it.
