### ISSUE TITLE
Add Ability to Disable Combinational Loop Detection

### ISSUE THREAD

**Issue by jackkoenig** [freechipsproject/firrtl#600]
This is problematic for people when there are false loops.

Perhaps it would be nice to add a bit-level combinational loop checker that verifies if a combinational loop is real or not.

**Comment by sdtwigg** [comment]
Somewhat amusingly, this does match what verilator will complain about.

**Comment by mysoreanoop** [comment]
Is there any update on this? Would the bit-level combination loop checker be implemented sometime? Cause it would be better to have the combinational loops checking on for genuine cases, right?

**Comment by aswaterman** [comment]
The conservative algorithm is still in force. I could be wrong, but disabling it might cause problems downstream: later compiler passes might fail to terminate in the presence of cycles in the combinational logic graph.

Jack’s suggestion remains interesting, but to avoid Verilator false positives, we’d need to do more than bit-level analysis: we’d also need to transform the RTL, expanding UInts into Vecs, etc.  And we’d probably need to restrict the transformation to bitwise operators, else we’d be getting into the business of emitting gate-level netlists for arithmetic circuits.  It makes the status quo seem not so bad.
