### ISSUE TITLE
Make Markers in Annotations Public

### ISSUE THREAD

**Issue by jackkoenig** [freechipsproject/firrtl#609]
This could eliminate code duplication in Chisel. It's [probably] impossible to have complete code-share for Chisel and Firrtl annotations since the Chisel objects are very different than Firrtl's Named things, but at least sharing the marker in the marker pattern (for example, see [DontTouchAnnotation](https://github.com/freechipsproject/firrtl/blob/master/src/main/scala/firrtl/transforms/OptimizationAnnotations.scala#L12)) would be somewhat better.

**Comment by jackkoenig** [comment]
Will be made obsolete by annotations refactor

**Comment by azidar** [comment]
Related to #704

**Comment by azidar** [comment]
made obsolete by #721
