### ISSUE TITLE
issue for chisel to print macros into the RTL

### ISSUE THREAD

**Issue by apolonic** [freechipsproject/firrtl#625]
my trend is about FPGA implementation. In some case you don't want the compiler optimize a specified module, you may use such macros in the RTL like:

case 1

>  wire your_wires /*synthesis syn_keep = 1 */

case 2

> (* keep = "true" *)
> reg your_regs

case 3

> (* keep_hierarchy = "yes"*)
> moudle_name instance_name (...);

so it looks like a special printf that you can print the macros as a string into the RTL code, as well as you can define which signal/wire/port/module/instance which such a printf can drop the archer to. This issue could be related to firrtl too.

**Comment by seldridge** [comment]
Duplicate of #687. Future discussion will occur there.
