### ISSUE TITLE
Zero Width Semantics?

### ISSUE THREAD

**Issue by donggyukim** [freechipsproject/firrtl#650]
What's the expected result when I have `cat(a, b, c)` with `b`'s width being zero? I expected `cat(a, c)`, but I got `cat(a, UInt<1>(0), c)`.

**Comment by aswaterman** [comment]
Did the ```UInt<1>(0)``` come from Chisel, or did Firrtl generate it?  Firrtl's spec agrees with you; cat'ing with a zero-width signal should not increase the width.

**Comment by azidar** [comment]
This is a firrtl bug, I'll submit a pr tomorrow
