### ISSUE TITLE
Annotating a module IO with DontTouch that will get de-duplicated fails

### ISSUE THREAD

**Issue by colinschmidt** [freechipsproject/firrtl#689]
I think in this particular case I would like the modules to be de-duplicated but leave the debug port (i.e. don't dead code eliminate it).

```
Exception in thread "main" firrtl.transforms.DontTouchAnnotation$DontTouchNotFoundException: Component marked DONT Touch (LaneSequencer_1.io_debug) not found!
```

**Comment by jackkoenig** [comment]
My bad, I had a fix for this and then got sidetracked.

This is actually a duplicate of #593 although DCE causes this to be an error.

**Comment by colinschmidt** [comment]
Thanks. Easy to workaround for now.
