### ISSUE TITLE
Constant Propagation Improvements

### ISSUE THREAD

**Issue by jackkoenig** [freechipsproject/firrtl#701]
- [ ] Propagate multiple inversions of the same signal
- [ ] Propagate arithmetic operators

**Comment by albert-magyar** [comment]
Closing this, as there is extensive support for constant propagation of arithmetic. To take advantage of the "double negation pattern" would require a restructuring of how constant propagation works quite a bit. This might be the goal of a future strength reduction transform and/or a motivating use case for keeping complex expression trees intact.
