### ISSUE TITLE
Check op input types (mul) in CheckTypes

### ISSUE THREAD

**Issue by azidar** [freechipsproject/firrtl#755]
* **Type of issue**
  - Bug report

* **If the current behavior is a bug, please provide the steps to reproduce the problem:**
For release candidate 1.1, a line like `node _T_162 = mul(_T_160, _T_161) @[multiplier.scala 102:43]` will trigger the following, if the input arguments are different types.

* **Impact**
  - no functional change

**Comment by seldridge** [comment]
Already fixed.
