### ISSUE TITLE
smems of zero-width fields throw exceptions

### ISSUE THREAD

**Issue by aswaterman** [freechipsproject/firrtl#757]
I know that there are lots of issues with zero-width things; this one is specific to the handling of memories.  Making a memory of a zero-width thing, or of a bundle that contains a zero-width thing, blows up.

* **Type of issue**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Other enhancement

* **If the current behavior is a bug, please provide the steps to reproduce the problem:**
 
Write the following Chisel code:

```SyncReadMem(2, UInt(0.W)).read(0.U, true.B)```

  * **What is the current behavior?**

```Exception in thread "main" firrtl.FIRRTLException: Unknown type encountered in bitWidth: UnknownType```

  * **Please tell us about your environment:**

Chisel 97871178cb511063965f971b768f91c289c4776f
Firrtl b90fc784a1819c1d7905910130a7da022214bc22

**Comment by grebe** [comment]
See also #666
