### ISSUE TITLE
mports without a declared mem hard errors

### ISSUE THREAD

**Issue by grebe** [freechipsproject/firrtl#796]
* **Type of issue**
  - [x ] Bug report

* **If the current behavior is a bug, please provide the steps to reproduce the problem:**
  * **If possible, please directly provide the FIRRTL file or a relevant fragment if the file is large**
```
circuit testTestModule :
  module testTestModule :
    input clock : Clock
    input reset : UInt<1>
    output io : {flip in : UInt<10>, out : UInt<10>}

    node _T_10 = bits(io.in, 1, 0)
    read mport _T_11 = m[_T_10], clock
    io.out <= _T_11
```
  * **What is the current behavior?**
Hard error, says to file an issue
  * **What is the expected behavior?**
It should say that m is not declared as a memory.

  * **Please tell us about your environment:**
    (examples)
    - version: `1.1.0`
    - OS: `OS X 10.13.4`

* **What is the use case for changing the behavior?**
See [the related Chisel issue](https://github.com/freechipsproject/chisel3/issues/815) for more information. In short, `new Mem()` (as opposed to `Mem()`) gives an inscrutable error message.

* **Impact**
  - [ x ] API addition (no impact on existing code)

* **Development Phase**
  - [ x ] request

**Comment by seldridge** [comment]
We need to check and see if this is still an issue. The likely solution is a better error message.
