### ISSUE TITLE
FIR crashes during the ByteBuffer conversion

### ISSUE THREAD

**Issue by tampler** [freechipsproject/firrtl#891]
**Type of issue**: bug report 

**Description**: I'm trying to **convert Float to its binary representation** and feed as an input to the circuit.
I'm using **Java ByteBuffer for this**. Here's my snippet

```scala

class Ram_sdp (dw:Int = 4, aw:Int = 4, pipe: Bool = false.B) extends Module {
  val io = IO (new Bundle {
    val wen   = Input (Bool())
    val waddr = Input (UInt(aw.W))
    val wdata = Input (UInt(dw.W))
    val ren   = Input (Bool())
    val raddr = Input (UInt(aw.W))
    val rdata = Output (UInt(dw.W))
  })

class RamUnitTest (c: Ram_sdp) extends PeekPokeTester (c) {

  val bb = java.nio.ByteBuffer.allocate(4) // transforms float -> int
 // Float to Binary conversion class
  implicit class float2Int (data:Float) {

    def f2Hex (): Int = {
      bb.putFloat (data)
      bb.flip      
      val res = bb.getInt 
      bb.clear
      res
    }
}
...
  var wdata = 0
  for (i <- 0 until xlen)
    for (j <- 0 until ylen) {

      wdata = amat.get(i,j).toFloat.f2Hex

      poke (uut.wen, 1)
      poke (uut.waddr, i*xlen + j)
      poke (uut.wdata, wdata ) // <<<<<<<<<<<<<< FIR Crashes here !!!
      step(1)
    }

```
When I run this with: 
A. test:runMain myPkg.RamMain --is-verbose the test passes with default **treadle** backend
B. test: runMain myPkg.RamMain --is-verbose --backend-name **firrtl** - it crashes with the following message:

Circuit state created
[info] [0.001] SEED 1537288906919
[info] [0.014]   POKE io_wen <- 0
[info] [0.014]   POKE io_ren <- 0
[info] [0.014] STEP 0 -> 1
[info] [0.022]   POKE io_wen <- 1
[info] [0.023]   POKE io_waddr <- 0
Error: poke(io_wdata, 1065082931)
firrtl_interpreter.InterpreterException: error: ConcreteUInt(1065082931, 4) bad width 4 needs 30
	at firrtl_interpreter.ConcreteUInt.<init>(Concrete.scala:371)

**Comment by azidar** [comment]
I believe this is a firrtl interpreter issue, please submit this issue there: https://github.com/freechipsproject/firrtl-interpreter
