### ISSUE TITLE
firrtl build crashes

### ISSUE THREAD

**Issue by luudee** [freechipsproject/firrtl#907]
Any ideas/suggestions ?

sbt -v compile
[process_args] java_version = '8'
# Executing command line:
java
-Xms1024m
-Xmx1024m
-XX:ReservedCodeCacheSize=128m
-XX:MaxMetaspaceSize=256m
-jar
/usr/share/sbt/bin/sbt-launch.jar
compile

[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /share/risc-v/rocket-chip/firrtl-1/project
[info] Loading settings from build.sbt ...
[info] Set current project to firrtl (in build file:/share/risc-v/rocket-chip/firrtl-1/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Compiling 92 Scala sources and 5 Java sources to /share/risc-v/rocket-chip/firrtl-1/target/scala-2.12/classes ...
[warn] /share/risc-v/rocket-chip/firrtl-1/src/main/scala/firrtl/Emitter.scala:544:9: match may not be exhaustive.
[warn] It would fail on the following input: (_, _)
[warn]         (dir, tpe) match {
[warn]         ^
[warn] /share/risc-v/rocket-chip/firrtl-1/src/main/scala/firrtl/passes/InferWidths.scala:226:60: match may not be exhaustive.
[warn] It would fail on the following inputs: (AnalogType(_), BundleType(_)), (AnalogType(_), ClockType), (AnalogType(_), FixedType(_, _)), (AnalogType(_), SIntType(_)), (AnalogType(_), Type()), (AnalogType(_), UIntType(_)), (AnalogType(_), VectorType(_, _)), (AnalogType(_), _), (BundleType(_), AnalogType(_)), (BundleType(_), ClockType), (BundleType(_), FixedType(_, _)), (BundleType(_), SIntType(_)), (BundleType(_), Type()), (BundleType(_), UIntType(_)), (BundleType(_), VectorType(_, _)), (BundleType(_), _), (ClockType, BundleType(_)), (ClockType, FixedType(_, _)), (ClockType, Type()), (ClockType, UIntType(_)), (ClockType, VectorType(_, _)), (ClockType, _), (FixedType(_, _), AnalogType(_)), (FixedType(_, _), BundleType(_)), (FixedType(_, _), ClockType), (FixedType(_, _), SIntType(_)), (FixedType(_, _), Type()), (FixedType(_, _), UIntType(_)), (FixedType(_, _), VectorType(_, _)), (FixedType(_, _), _), (SIntType(_), BundleType(_)), (SIntType(_), FixedType(_, _)), (SIntType(_), Type()), (SIntType(_), UIntType(_)), (SIntType(_), VectorType(_, _)), (SIntType(_), _), (Type(), AnalogType(_)), (Type(), BundleType(_)), (Type(), ClockType), (Type(), FixedType(_, _)), (Type(), SIntType(_)), (Type(), Type()), (Type(), UIntType(_)), (Type(), VectorType(_, _)), (Type(), _), (UIntType(_), BundleType(_)), (UIntType(_), FixedType(_, _)), (UIntType(_), Type()), (UIntType(_), VectorType(_, _)), (UIntType(_), _), (VectorType(_, _), BundleType(_)), (VectorType(_, _), ClockType), (VectorType(_, _), FixedType(_, _)), (VectorType(_, _), Type()), (VectorType(_, _), UIntType(_)), (VectorType(_, _), _), (_, AnalogType(_)), (_, BundleType(_)), (_, ClockType), (_, FixedType(_, _)), (_, SIntType(_)), (_, Type()), (_, UIntType(_)), (_, VectorType(_, _)), (_, _)
[warn]     def get_constraints_t(t1: Type, t2: Type): Seq[WGeq] = (t1,t2) match {
[warn]                                                            ^
[warn] /share/risc-v/rocket-chip/firrtl-1/src/main/scala/firrtl/passes/Resolves.scala:87:42: match may not be exhaustive.
[warn] It would fail on the following inputs: (MInfer, _), (MPortDir(), _), (MRead, _), (MReadWrite, _), (MWrite, _), (_, MInfer), (_, MPortDir()), (_, MRead), (_, MReadWrite), (_, MWrite), (_, _)
[warn]         case Some(p) => mports(e.name) = (p, dir) match {
[warn]                                          ^
[warn] /share/risc-v/rocket-chip/firrtl-1/src/main/scala/firrtl/proto/FromProto.scala:142:76: match may not be exhaustive.
[warn] It would fail on the following inputs: MEMORY_PORT_DIRECTION_UNKNOWN, UNRECOGNIZED
[warn]   def convert(mportdir: Firrtl.Statement.MemoryPort.Direction): MPortDir = mportdir match {
[warn]                                                                            ^
[warn] /share/risc-v/rocket-chip/firrtl-1/src/main/scala/firrtl/proto/FromProto.scala:251:5: match may not be exhaustive.
[warn] It would fail on the following inputs: PORT_DIRECTION_UNKNOWN, UNRECOGNIZED
[warn]     dir match {
[warn]     ^
[warn] /share/risc-v/rocket-chip/firrtl-1/src/main/scala/firrtl/transforms/ConstantPropagation.scala:67:42: match may not be exhaustive.
[warn] It would fail on the following inputs: (Literal(), _), (SIntLiteral(_, _), UIntLiteral(_, _)), (SIntLiteral(_, _), _), (UIntLiteral(_, _), SIntLiteral(_, _)), (UIntLiteral(_, _), _), (_, Literal()), (_, SIntLiteral(_, _)), (_, UIntLiteral(_, _)), (_, _)
[warn]     def fold(c1: Literal, c2: Literal) = (c1, c2) match {
[warn]                                          ^
[warn] /share/risc-v/rocket-chip/firrtl-1/src/main/scala/firrtl/transforms/DeadCodeElimination.scala:156:27: match may not be exhaustive.
[warn] It would fail on the following input: Port(_, _, (x: firrtl.ir.Direction forSome x not in (Input, Output)), (x: firrtl.ir.Type forSome x not in firrtl.ir.AnalogType))
[warn]         ext.ports.foreach {
[warn]                           ^
[warn] /share/risc-v/rocket-chip/firrtl-1/src/main/scala/firrtl/Driver.scala:93:40: method getAnnotationFileName in class FirrtlExecutionOptions is deprecated (since 1.1): Use FirrtlOptions.annotationFileNames instead
[warn]     val oldAnnoFileName = firrtlConfig.getAnnotationFileName(optionsManager)
[warn]                                        ^
[warn] /share/risc-v/rocket-chip/firrtl-1/src/main/scala/firrtl/graph/DiGraph.scala:194:29: class Stack in package mutable is deprecated (since 2.12.0): Stack is an inelegant and potentially poorly-performing wrapper around List. Use a List assigned to a var instead.
[warn]     val stack = new mutable.Stack[T]
[warn]                             ^
[warn] /share/risc-v/rocket-chip/firrtl-1/src/main/scala/firrtl/graph/DiGraph.scala:210:33: class Stack in package mutable is deprecated (since 2.12.0): Stack is an inelegant and potentially poorly-performing wrapper around List. Use a List assigned to a var instead.
[warn]     val callStack = new mutable.Stack[StrongConnectFrame[T]]
[warn]                                 ^
[warn] /share/risc-v/rocket-chip/firrtl-1/src/main/scala/firrtl/passes/clocklist/ClockList.scala:25:23: method getChildrenMap in object WiringUtils is deprecated (since 1.1.1): Use DiGraph/InstanceGraph
[warn]     val childrenMap = getChildrenMap(c)
[warn]                       ^
[warn] /share/risc-v/rocket-chip/firrtl-1/src/main/scala/firrtl/passes/clocklist/ClockList.scala:27:20: method getLineage in object WiringUtils is deprecated (since 1.1.1): Use DiGraph/InstanceGraph
[warn]     val lineages = getLineage(childrenMap, top)
[warn]                    ^
[warn] /share/risc-v/rocket-chip/firrtl-1/src/main/scala/firrtl/passes/clocklist/ClockListUtils.scala:21:61: class Lineage in package wiring is deprecated (since 1.1.1): Use DiGraph/InstanceGraph
[warn]   def getSourceList(moduleMap: Map[String, DefModule])(lin: Lineage): Seq[String] = {
[warn]                                                             ^
[warn] /share/risc-v/rocket-chip/firrtl-1/src/main/scala/firrtl/passes/clocklist/ClockListUtils.scala:39:90: class Lineage in package wiring is deprecated (since 1.1.1): Use DiGraph/InstanceGraph
[warn]   def getOrigins(connects: Connects, me: String, moduleMap: Map[String, DefModule])(lin: Lineage): Map[String, String] = {
[warn]                                                                                          ^
[warn] /share/risc-v/rocket-chip/firrtl-1/src/main/scala/firrtl/passes/memlib/ReplaceMemMacros.scala:217:68: method getMyAnnotations in class Transform is deprecated (since 1.1): Just collect the actual Annotation types the transform wants
[warn]       case _ => throwInternalError(s"execute: getMyAnnotations - ${getMyAnnotations(state)}")
[warn]                                                                    ^
[warn] there was one unchecked warning; re-run with -unchecked for details
[warn] there were 32 feature warnings; re-run with -feature for details
[warn] 17 warnings found
[warn] javac exited with exit code -1
[error] ## Exception when compiling 97 sources to /share/risc-v/rocket-chip/firrtl-1/target/scala-2.12/classes
[error] Cannot run program "javac" (in directory "/share/risc-v/rocket-chip/firrtl-1"): error=2, No such file or directory
[error] java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[error] scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
[error] scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:102)
[error] scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$anonfun$runBuffered$1(ProcessBuilderImpl.scala:150)
[error] scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:12)
[error] sbt.internal.inc.javac.JavacLogger.buffer(JavacProcessLogger.scala:39)
[error] scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:150)
[error] scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:116)
[error] sbt.internal.inc.javac.ForkedJava$.$anonfun$launch$3(ForkedJava.scala:44)
[error] sbt.internal.inc.javac.ForkedJava$.$anonfun$launch$3$adapted(ForkedJava.scala:37)
[error] sbt.internal.inc.javac.ForkedJava$.$anonfun$withArgumentFile$1(ForkedJava.scala:66)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
[error] sbt.internal.inc.javac.ForkedJava$.withArgumentFile(ForkedJava.scala:63)
[error] sbt.internal.inc.javac.ForkedJava$.launch(ForkedJava.scala:37)
[error] sbt.internal.inc.javac.ForkedJavaCompiler.run(ForkedJava.scala:90)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$11(AnalyzingJavaCompiler.scala:130)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:196)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:120)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:106)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:134)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:117)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:110)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:57)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:61)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1429)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1403)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] sbt.std.Transform$$anon$4.work(System.scala:66)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] sbt.Execute.work(Execute.scala:271)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
[error]            
[error] java.io.IOException: Cannot run program "javac" (in directory "/share/risc-v/rocket-chip/firrtl-1"): error=2, No such file or directory
[error]         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[error]         at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:102)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$anonfun$runBuffered$1(ProcessBuilderImpl.scala:150)
[error]         at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:12)
[error]         at sbt.internal.inc.javac.JavacLogger.buffer(JavacProcessLogger.scala:39)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:150)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:116)
[error]         at sbt.internal.inc.javac.ForkedJava$.$anonfun$launch$3(ForkedJava.scala:44)
[error]         at sbt.internal.inc.javac.ForkedJava$.$anonfun$launch$3$adapted(ForkedJava.scala:37)
[error]         at sbt.internal.inc.javac.ForkedJava$.$anonfun$withArgumentFile$1(ForkedJava.scala:66)
[error]         at sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
[error]         at sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
[error]         at sbt.internal.inc.javac.ForkedJava$.withArgumentFile(ForkedJava.scala:63)
[error]         at sbt.internal.inc.javac.ForkedJava$.launch(ForkedJava.scala:37)
[error]         at sbt.internal.inc.javac.ForkedJavaCompiler.run(ForkedJava.scala:90)
[error]         at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$11(AnalyzingJavaCompiler.scala:130)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:196)
[error]         at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:120)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:106)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:134)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:91)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:117)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error]         at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error]         at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:110)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:57)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error]         at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error]         at sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error]         at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:61)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1429)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1403)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.io.IOException: error=2, No such file or directory
[error]         at java.lang.UNIXProcess.forkAndExec(Native Method)
[error]         at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
[error]         at java.lang.ProcessImpl.start(ProcessImpl.java:134)
[error]         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[error]         at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:102)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$anonfun$runBuffered$1(ProcessBuilderImpl.scala:150)
[error]         at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:12)
[error]         at sbt.internal.inc.javac.JavacLogger.buffer(JavacProcessLogger.scala:39)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:150)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:116)
[error]         at sbt.internal.inc.javac.ForkedJava$.$anonfun$launch$3(ForkedJava.scala:44)
[error]         at sbt.internal.inc.javac.ForkedJava$.$anonfun$launch$3$adapted(ForkedJava.scala:37)
[error]         at sbt.internal.inc.javac.ForkedJava$.$anonfun$withArgumentFile$1(ForkedJava.scala:66)
[error]         at sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
[error]         at sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
[error]         at sbt.internal.inc.javac.ForkedJava$.withArgumentFile(ForkedJava.scala:63)
[error]         at sbt.internal.inc.javac.ForkedJava$.launch(ForkedJava.scala:37)
[error]         at sbt.internal.inc.javac.ForkedJavaCompiler.run(ForkedJava.scala:90)
[error]         at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$11(AnalyzingJavaCompiler.scala:130)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:196)
[error]         at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:120)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:106)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:134)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:91)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:117)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error]         at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error]         at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:110)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:57)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error]         at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error]         at sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error]         at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:61)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1429)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1403)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / compileIncremental) java.io.IOException: Cannot run program "javac" (in directory "/share/risc-v/rocket-chip/firrtl-1"): error=2, No such file or directory
[error] Total time: 37 s, completed Oct 4, 2018 11:40:36 PM

**Comment by edwardcwang** [comment]
Is the JDK installed and functional by any chance?

```
 [error] Cannot run program "javac" (in directory "/share/risc-v/rocket-chip/firrtl-1"): error=2, No such file or directory
```

**Comment by luudee** [comment]
Ahh, the JDK was installed, but the JDK-development was not.

Thank you for pointing that out Edward !
