### ISSUE TITLE
xorR is broken in unittest?

### ISSUE THREAD

**Issue by zinechant** [freechipsproject/firrtl#993]
**Type of issue**: bug report 

I am new to chisel world. While I am exploring, I noticed that the xorR is broken in firrtl backend for unit tests.

There were discussions about broken of reduction operators. #356 
But it seems xorR is still tied to the lowest bit.

A simple repo testing xorR:
https://github.com/zinechant/xor_reduce

Regards,
Chen

**Comment by zinechant** [comment]
It seems firrtl-intepreter repo is a better place to discuss this bug. 
https://github.com/freechipsproject/firrtl-interpreter/issues/146

Please feel free to close this one.

**Comment by edwardcwang** [comment]
Closing per request of original poster.
